node_configuration:
  topic_name: '/zed2/zed_node/right/image_rect_color/compressed' #'/zed2i/zed_node/right/image_rect_color'
  node_name: 'bluberry_detection'

object_detection:
  model: 'YOLOV8'
  weights_path: '/home/pqbas/catkin_ws/src/blueberry-detection-ros/weights/yolov8m_best.pt'

count_configuration:
  tracking_flag: False #True
  count_mode: 'vertical'
  threshold_track: 320
  direction: 'top2down'
  
visualization:
  show_image: True


  
